version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app          # Sync host code
      - /app/node_modules        # Preserve container's node_modules
    ports:
      - "3000:3000"
      